# 异常（Exception）
###12.6.2 重新抛出异常
重抛异常会把异常抛给上一级环境中的异常处理，同一个try块的后续catch子句将被忽略。异常的所有信息都会得以保存。
如果只是把当前异常对象重新抛出，那么`printStackTrace()`方法显示原来异常抛出点的调用栈信息，而不是重新抛出点的信息。想要更新这个信息，可以调用`fillInStackTrace()`方法，将返回一个`Throwable`对象，他是通过吧当前调用栈信息填入原来那个异常对象而建立的。

> 有可能在捕获到异常之后抛出另一种异常，这么做的话得到的效果类似`fillInStackTrace()`，<strong><u>有关原来的数据会丢失，剩下的是新抛出点有关的异常信息。</u></strong>
[P259]()

> <strong><u>异常对象都是new在堆上创建的对象，所以垃圾回收器会自动把他们清理掉。</u></strong>


###12.6.3 异常链
在捕获一个异常之后抛出另一个异常，并且希望把原始异常信息保存下来， 这种称为<strong>异常连</strong> JDK1.4之前必须自己写代码保存，现在所有的`Throwable`子类在构造器中都可以接受一个<i style="color:red;">*cause*</i>对象作为参数这个<i style="color:red;">*cause*</i>就是用来表示原始的异常

